// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authorization.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PolicyRequest struct {
	Role                 string   `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Tenant               string   `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Resource             string   `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Action               string   `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PolicyRequest) Reset()         { *m = PolicyRequest{} }
func (m *PolicyRequest) String() string { return proto.CompactTextString(m) }
func (*PolicyRequest) ProtoMessage()    {}
func (*PolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dbbe58d1e51a797, []int{0}
}

func (m *PolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolicyRequest.Unmarshal(m, b)
}
func (m *PolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolicyRequest.Marshal(b, m, deterministic)
}
func (m *PolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolicyRequest.Merge(m, src)
}
func (m *PolicyRequest) XXX_Size() int {
	return xxx_messageInfo_PolicyRequest.Size(m)
}
func (m *PolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PolicyRequest proto.InternalMessageInfo

func (m *PolicyRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *PolicyRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *PolicyRequest) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *PolicyRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

type PolicyResponse struct {
	When                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=when,proto3" json:"when,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PolicyResponse) Reset()         { *m = PolicyResponse{} }
func (m *PolicyResponse) String() string { return proto.CompactTextString(m) }
func (*PolicyResponse) ProtoMessage()    {}
func (*PolicyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dbbe58d1e51a797, []int{1}
}

func (m *PolicyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolicyResponse.Unmarshal(m, b)
}
func (m *PolicyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolicyResponse.Marshal(b, m, deterministic)
}
func (m *PolicyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolicyResponse.Merge(m, src)
}
func (m *PolicyResponse) XXX_Size() int {
	return xxx_messageInfo_PolicyResponse.Size(m)
}
func (m *PolicyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PolicyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PolicyResponse proto.InternalMessageInfo

func (m *PolicyResponse) GetWhen() *timestamp.Timestamp {
	if m != nil {
		return m.When
	}
	return nil
}

func init() {
	proto.RegisterType((*PolicyRequest)(nil), "authorization.v1.PolicyRequest")
	proto.RegisterType((*PolicyResponse)(nil), "authorization.v1.PolicyResponse")
}

func init() { proto.RegisterFile("authorization.proto", fileDescriptor_1dbbe58d1e51a797) }

var fileDescriptor_1dbbe58d1e51a797 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x25, 0x31, 0x14, 0x1d, 0xad, 0xca, 0x8a, 0x12, 0x82, 0xd0, 0x92, 0x93, 0x78, 0xd8, 0x90,
	0x7a, 0xf3, 0xe4, 0xc7, 0x1f, 0x90, 0xe0, 0xc9, 0xdb, 0x36, 0x8c, 0x4d, 0x20, 0xdd, 0x89, 0xbb,
	0x93, 0x48, 0x3d, 0xfa, 0x17, 0xfc, 0x69, 0xfe, 0x05, 0x7f, 0x88, 0x74, 0xb7, 0x11, 0x2b, 0x78,
	0xdb, 0x99, 0xf7, 0xde, 0xbe, 0xf7, 0x06, 0x4e, 0x54, 0xc7, 0x15, 0x99, 0xfa, 0x4d, 0x71, 0x4d,
	0x5a, 0xb6, 0x86, 0x98, 0xc4, 0xf1, 0xf6, 0xb2, 0xcf, 0x93, 0xc9, 0x82, 0x68, 0xd1, 0x60, 0xe6,
	0xf0, 0x79, 0xf7, 0x9c, 0x71, 0xbd, 0x44, 0xcb, 0x6a, 0xd9, 0x7a, 0x49, 0x72, 0xbe, 0x21, 0xa8,
	0xb6, 0xce, 0x94, 0xd6, 0xc4, 0x4e, 0x6a, 0x3d, 0x9a, 0x12, 0x8c, 0x1f, 0xa8, 0xa9, 0xcb, 0x55,
	0x81, 0x2f, 0x1d, 0x5a, 0x16, 0x02, 0x22, 0x43, 0x0d, 0xc6, 0xc1, 0x34, 0xb8, 0xd8, 0x2b, 0xdc,
	0x5b, 0x9c, 0xc1, 0x88, 0x51, 0x2b, 0xcd, 0x71, 0xe8, 0xb6, 0x9b, 0x49, 0x24, 0xb0, 0x6b, 0xd0,
	0x52, 0x67, 0x4a, 0x8c, 0x77, 0x1c, 0xf2, 0x33, 0xaf, 0x35, 0xaa, 0x5c, 0x3b, 0xc5, 0x91, 0xd7,
	0xf8, 0x29, 0xbd, 0x81, 0xc3, 0xc1, 0xd0, 0xb6, 0xa4, 0x2d, 0x0a, 0x09, 0xd1, 0x6b, 0x85, 0xda,
	0x39, 0xee, 0xcf, 0x12, 0xe9, 0xf3, 0xca, 0xa1, 0x90, 0x7c, 0x1c, 0x0a, 0x15, 0x8e, 0x37, 0x5b,
	0xc1, 0xf8, 0xf6, 0xf7, 0x15, 0x44, 0x05, 0x07, 0xf7, 0x06, 0x15, 0xa3, 0xff, 0x58, 0x4c, 0xe4,
	0xdf, 0x2b, 0xc9, 0xad, 0x8e, 0xc9, 0xf4, 0x7f, 0x82, 0xcf, 0x94, 0x9e, 0xbe, 0x7f, 0x7e, 0x7d,
	0x84, 0x47, 0x29, 0x64, 0x7d, 0x9e, 0xb5, 0x0e, 0xbb, 0x0e, 0x2e, 0xef, 0xa2, 0xa7, 0xb0, 0xcf,
	0xe7, 0x23, 0x17, 0xed, 0xea, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x26, 0x99, 0x3e, 0x62, 0xa2, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthorizationClient is the client API for Authorization service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthorizationClient interface {
	CreatePolicy(ctx context.Context, in *PolicyRequest, opts ...grpc.CallOption) (*PolicyResponse, error)
}

type authorizationClient struct {
	cc *grpc.ClientConn
}

func NewAuthorizationClient(cc *grpc.ClientConn) AuthorizationClient {
	return &authorizationClient{cc}
}

func (c *authorizationClient) CreatePolicy(ctx context.Context, in *PolicyRequest, opts ...grpc.CallOption) (*PolicyResponse, error) {
	out := new(PolicyResponse)
	err := c.cc.Invoke(ctx, "/authorization.v1.Authorization/CreatePolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorizationServer is the server API for Authorization service.
type AuthorizationServer interface {
	CreatePolicy(context.Context, *PolicyRequest) (*PolicyResponse, error)
}

// UnimplementedAuthorizationServer can be embedded to have forward compatible implementations.
type UnimplementedAuthorizationServer struct {
}

func (*UnimplementedAuthorizationServer) CreatePolicy(ctx context.Context, req *PolicyRequest) (*PolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePolicy not implemented")
}

func RegisterAuthorizationServer(s *grpc.Server, srv AuthorizationServer) {
	s.RegisterService(&_Authorization_serviceDesc, srv)
}

func _Authorization_CreatePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServer).CreatePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authorization.v1.Authorization/CreatePolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServer).CreatePolicy(ctx, req.(*PolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Authorization_serviceDesc = grpc.ServiceDesc{
	ServiceName: "authorization.v1.Authorization",
	HandlerType: (*AuthorizationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePolicy",
			Handler:    _Authorization_CreatePolicy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authorization.proto",
}
